### ISSUE TITLE
binary_to_float/1 not defined

### ISSUE THREAD

**Issue by junjiemars** [ChicagoBoss/boss_db#210]
I'd got the following issue when making:
src/boss_record_lib.erl:126: function binary_to_float/1 undefined
ERROR: compile failed while processing /opt/erlang/ChicagoBoss.git/deps/boss_db: rebar_abort
make: *** [all] Error 1

My erlang env is 
Erlang R15B03 (erts-5.9.3.1) [source] [smp:2:2] [async-threads:0] [hipe] [kernel-poll:false]
I found the binary_to_float doesn't existing my Erlang env, 

So, How to build boss_db in my Erlang env

**Comment by davidw** [comment]
You need a more recent Erlang to work with Chicago Boss.

**Comment by junjiemars** [comment]
Yes, It's run on Erlang OTP_16B03-1.
